### ISSUE TITLE
Ubuntu 16.04 linux compile fails

### ISSUE THREAD

**Issue by geoffmcl** [geoffmcl/cpp-markdown#3]
**UGH**! Unable to compile in Ubuntu 16.04 64-bit, using gcc 5.4.0, and the installed boost 1.58...

Any help appreciated... thanks...

**Comment by geoffmcl** [comment]
So far I have applied the following patches -

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7b8402c..c5ab2c2 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -42,7 +42,7 @@ endif ()
 set(Boost_USE_STATIC_LIBS ON) 
 ### set(Boost_USE_MULTITHREADED ON)  
 ### set(Boost_USE_STATIC_RUNTIME OFF) 
-find_package(Boost 1.62.0 COMPONENTS regex REQUIRED)
+find_package(Boost COMPONENTS iostreams regex REQUIRED)
 message(STATUS "*** Found Boost inc ${Boost_INCLUDE_DIRS}, lib ${Boost_LIBRARIES}")
 include_directories( ${Boost_INCLUDE_DIRS} )
 list(APPEND add_LIBS ${Boost_LIBRARIES} )
diff --git a/src/main.cpp b/src/main.cpp
index 65d73f1..f7d286c 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -14,7 +14,7 @@
 #include <string>
 
 #include <boost/optional.hpp>
-//#include <boost/regex.hpp> // For the 'test' option
+#include <boost/regex.hpp> // For the 'test' option
 
 #include "markdown.h"
 ```

But still **FAILS** with -

```
markdown.cpp:(.text+0x1f70): undefined reference to `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
```

The boost libraries are found -

```
-- Found the following Boost libraries:
--   iostreams
--   regex
-- *** Found Boost inc /usr/include, lib /usr/lib/x86_64-linux-gnu/libboost_iostreams.a;/usr/lib/x86_64-linux-gnu/libboost_regex.a
```
And are included in the link -

```
/usr/bin/c++   -O3 -DNDEBUG   CMakeFiles/cpp-markdown.dir/src/main.cpp.o  -o cpp-markdown -rdynamic -Wl,-Bstatic -lboost_iostreams -lboost_regex libcppmarkdown.a -Wl,-Bdynamic 
```

**HELP NEEDED** Thanks...

**Comment by geoffmcl** [comment]
Pushed the above patch to `next` branch, and it **still** builds in Windows 10 64-bit, using MSVC14 2015 Community install...

But **still** fails in Ubuntu! **YUCK**!!!

**HELP NEEDED** Thanks...

**Comment by geoffmcl** [comment]
**DRAT DRAT DRAT** the build **also** `fails` in RPI Raspbian 8.0 (jessie), with boost 1.55, with seemingly the **same** problems, and perhaps others - ` undefined reference to boost::re_detail::perl_matcher...`...

This **must** be solvable! **HELP** Thanks...

**Comment by geoffmcl** [comment]
After doing `sudo apt-get install libboost-all-dev`, for boost 1.58, in Ubuntu 16.04 32-bits, `build` also **FAILS** with **same** error - **YUCK**...

Seems the only thing to try is a boost build and install of a **later** boost version...

**Comment by geoffmcl** [comment]
From https://www.boost.org/users/history/version_1_67_0.html downloaded `boost_1_67_0.tar.gz`
```
in $HOME/downloads have
-rw-rw-r-- 1 geoff geoff 103363944 May  6 20:06 boost_1_67_0.tar.gz
```
Unzipped to `$HOME/projects/boost` creating `boost_1_67_0` folder... In that folder did -

```
./bootstrap.sh --prefix=$HOME/projects/install/boost_1_67_0
./b2 --prefix=$HOME/projects/install/boost_1_67_0
```
Waiting for **long** build to complete...

**Comment by geoffmcl** [comment]
Wow, it finished with - some newlines removed...
```
...updated 1254 targets...
The Boost C++ Libraries were successfully built!
The following directory should be added to compiler include paths:
    /home/geoff/projects/boost/boost_1_67_0
The following directory should be added to linker library paths:
    /home/geoff/projects/boost/boost_1_67_0/stage/lib
```
**Maybe** I do not need to actually do an `install`... just use the above... somehow...

But that will be tomorrow now...

**Comment by geoffmcl** [comment]
Ok, ended up installing it - `$ ./b2 --prefix=$HOME/projects/install/boost_1_67_0 install`...

Yes, I could probably have used `CMAKE_INCLUDE_PATH` and `CMAKE_LIBRARY_PATH` appropriately, but wanted to use `CMAKE_PREFIX_PATH`, where cmake will append `/include` and `/lib` when doing the finds...

So cleaned up the last `build` completely, and did `$ cmake .. -DCMAKE_PREFIX_PATH=$HOME/projects/install/boost_1_67_0 ...`, and **WOW** cmake did its job and **found** this **new** 1.67 boost...

```
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   iostreams
--   regex
-- *** Found Boost inc $HOME/projects/install/boost_1_67_0/include, 
   lib $HOME/projects/install/boost_1_67_0/lib/libboost_iostreams.a;$HOME/projects/install/boost_1_67_0/lib/libboost_regex.a
```

But it **still** FAILED! The main **error** had changed a little - `undefined reference to boost::re_detail_106700::perl_matcher...`, but looks to be the **same** crap!

Have tried reversing the **order** of these two libraries, **and** using the `shared` libraries, instead of the `static`

```
  lib $HOME/projects/install/boost_1_67_0/lib/libboost_regex.so;$HOME/projects/install/boost_1_67_0/lib/libboost_iostreams.so
```

**But still no go!***

Also noted some **strange** cmake warnings -

```
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106700
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:45 (find_package)

CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106700
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:45 (find_package)
```

In reviewing the cmake 3.5 `FindBoost.cmake` module, it seems the **latest** boost it had component dependencies for is boost 1.61.0. There is a suggested method for updating this block. But since I am already including iostreams and regex, this does not seem important...

**BUT** just to be **real** sure, I downloaded `boost_1_61_0.tar.gz`, unpacked it into `/media/geoff/backup/projects/boost_1_61_0`, built and installed it into `/media/geoff/backup/projects/install/boost_1_61_0`, and did yet another clean build with `cmake .. -DCMAKE_PREFIX_PATH=/media/geoff/backup/projects/install/boost_1_61_0 ...`

No cmake warnings this time -

```
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   iostreams
--   regex
-- *** Found Boost inc /media/geoff/backup/projects/install/boost_1_61_0/include, 
 lib /media/geoff/backup/projects/install/boost_1_61_0/lib/libboost_iostreams.a;/media/geoff/backup/projects/install/boost_1_61_0/lib/libboost_regex.a
```
But **still** the **same** error, of course using the boost version, `undefined reference to boost::re_detail_106100::perl_matcher...`...

Some references read -

```
https://stackoverflow.com/questions/40225571/regex-search-hpp56-undefined-reference-to-boostre-detail-106100perl-match
https://github.com/facebook/folly/issues/614
https://github.com/mapnik/mapnik/issues/3333
```

The latter suggests boost has to be built with `icu` support, `--with-icu`, which I did **not** do... maybe I need to rebuild `boost` yet again...

**BAH**! This is **too** much... will give it a rest before I tear out all my hair ;=))

**Comment by geoffmcl** [comment]
Opened a repo - https://github.com/geoffmcl/test-regex - to **test** some `boost::regex` code, but so far have been unable to replicate the problem here...

**Comment by geoffmcl** [comment]
Opened an [issue 1](https://github.com/geoffmcl/test-regex/issues/1) to seek example/sample code that shows the same problem as here...

**Comment by geoffmcl** [comment]
**SOLVED**, sort of...

Originally first built a `static` library holding most of the working code, then added a `main` module linking with that local library... That produced the above **link** problem...

First adding this source to the `test-regex` project - see [issue 1](https://github.com/geoffmcl/test-regex/issues/1) - in a `test-md` branch, where it compiled as `one`, **no problems**...

So added an option `BUILD_SEP_LIBRARY`, default to `OFF` here, to build as a combined source, and again **NO PROBLEM**...

No understanding why the `library + main` approach failed here in linux... It works fine in Windows...

But happy to get it compiled, and running... **PHEW**! so closing this...
